# Generated by Django 5.2.6 on 2025-09-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Example',
            new_name='NewModel',
        ),
        migrations.RenameField(
            model_name='newmodel',
            old_name='name',
            new_name='title',
        ),
    ]
