# Generated by Django 5.2.6 on 2025-09-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_testimonial_remove_project_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
